# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Increase timeout for slow commands (pyenv shims can be slow)
command_timeout = 1000

add_newline = true

[character]
success_symbol = '[➜](bold green)'

# [python]
# symbol = '👾 '
# pyenv_version_name = true

[directory]
truncate_to_repo = false
truncation_length = 2

[docker_context]
disabled = true

[aws]
format = 'on [$symbol$profile]($style) '
style = 'bold blue'
symbol = '🅰 '
[aws.profile_aliases]
Enterprise_Naming_Scheme-voidstars = 'void**'
