" =============================  GENERAL CONFIG  ==============================
let mapleader=","               "Change leader to a comma

"win 120 80                     "Make window 80 wide x 45 tall
set nocompatible                "Use vim defaults
set ru                          "Turn on ruler
set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set hidden                      "Buffers exist in the background
set ignorecase                  "Ignore case when searching
set wrapscan                    "Search wrap around the EOF
set smartcase                   "Override 'ignorecase' if search has uppercase
set incsearch                   "Do incremental searching
set hlsearch                    "Highlight searches
set nowrap                      "Don't wrap lines
set linebreak                   "Wrap lines at convenient points
set scrolloff=8                 "Start scrolling 8 lines away from margins
set sidescrolloff=15
set sidescroll=1
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
set autochdir " always set pwd to path of current file
"set cin
"set autoindent
"set smartindent
"set smarttab

"highlight characters past 80 columns
augroup vimrc_autocmds
  autocmd BufEnter * highlight OverLength ctermbg=darkgrey guibg=#592929
  autocmd BufEnter * match OverLength /\%80v.*/
augroup END

set foldnestmax=5               "deepest fold is 5 levels
set foldmethod=syntax           "fold by syntax
"set foldmethod=indent          "fold based on indent
"set nofoldenable               "dont fold by default

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

autocmd FileType ruby set sw=4 sts=4 et
autocmd FileType haml set sw=4 sts=4 et
autocmd FileType coffee set sw=4 sts=4 et
autocmd FileType scss set sw=4 sts=4 et
autocmd FileType erb set sw=4 sts=4 et

" Keep undo history across sessions, by storing in file.
silent !mkdir ~/.vim/backups > /dev/null 2>&1
set undodir=~/.vim/backups
set undofile

" Auto complete stuff
set wildmode=list:longest,full     "first list:longest then full
set wildmenu                       "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~        "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif


" ================================  MAPPINGS  ==================================

" jj to exit insert mode
imap jj <Esc>

" toggle fold open/closed with <S-Space> if over a fold
nnoremap <silent> <S-Space> @=(foldlevel('.')?'za':'l')<CR>

" Move between split windows with Ctrl + arrow keys
nnoremap <silent> <C-h> <C-w>h
nnoremap <silent> <C-l> <C-w>l
nnoremap <silent> <C-k> <C-w>k
nnoremap <silent> <C-j> <C-w>j

"make search results appear in middle of screen
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz

"clear searches with ESC
nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[

" syntax on "turn on syntax highlighting

" =============================  INIT VUNDLES  ==============================
" if filereadable(expand("~/.vim/vundles.vim"))
"   source ~/.vim/vundles.vim
" endif

if filereadable(expand("~/.vim/plugs.vim"))
  source ~/.vim/plugs.vim
endif


" ========================  VUNDLE/PLUGIN MAPPINGS  =========================

" Set some shortcuts for Tabularize
nmap <Leader>a= :Tabularize /=<CR>
vmap <Leader>a= :Tabularize /=<CR>
nmap <Leader>a: :Tabularize /:\zs<CR>
vmap <Leader>a: :Tabularize /:\zs<CR>

"NERDTree toggle set to capital T
map T :NERDTreeToggle<CR>
let g:NERDTreeWinSize = 20
let NERDTreeIgnore = ['\.pyc$','\.pyo$', '\.db$', '__pycache__']

if executable('rg')
  set grepprg=rg\ --color=never
  let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
  let g:ctrlp_use_caching = 0
endif

" CtrlP toggle set to leader + t
map <leader>t :CtrlP<CR>

" leader + shift + t => reload CtrlP
nnoremap <silent> <leader>T :ClearCtrlPCache<cr>\|:CtrlP<cr>
let g:ctrlp_custom_ignore = {
  \ 'file': '\v\.(pyc|pyo)$',
  \ }
"have CtrlP follow symlinks
let g:ctrlp_follow_symlinks = 1

"TComment remap to c key
map <leader>/ <c-_><c-_>

"Gundo - GUI Undo Tree (visualized)
map <leader>u :GundoToggle<CR>

" python folding - preview docstring in fold text
let g:SimpylFold_docstring_preview = 1

" set YouCompleteMe goto definition
" map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>
" let g:ycm_autoclose_preview_window_after_completion = 1
" let g:ycm_autoclose_preview_window_after_insertion = 1

" indent guide - minimum width, subtle highlighting
let g:indent_guides_guide_size = 1
let g:indent_guides_color_change_percent = 3
let g:indent_guides_enable_on_vim_startup = 1

" FZF (replaces Ctrl-P, FuzzyFinder and Command-T)
" set rtp+=/usr/local/opt/fzf
" set rtp+=~/.fzf
" nmap ; :Buffers<CR>
" nmap <Leader>r :Tags<CR>
" nmap <Leader>t :Files<CR>
" nmap <Leader>a :Ag<CR>

"Mappings for fugitive
map <leader>gb :Gblame<CR>
map <leader>gh :Gbrowse<CR>

" GitGutter
let g:gitgutter_sign_added = '∙'
let g:gitgutter_sign_modified = '∙'
let g:gitgutter_sign_removed = '∙'
let g:gitgutter_sign_modified_removed = '∙'
let g:gitgutter_realtime = 0

" ALE
let g:ale_sign_warning = '▲'
let g:ale_sign_error = '✗'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
highlight link ALEWarningSign String
highlight link ALEErrorSign Title

" Lightline
let g:lightline = {
\ 'colorscheme': 'wombat',
\ 'active': {
\   'left': [['mode', 'paste'], ['filename', 'modified']],
\   'right': [['lineinfo'], ['percent'], ['readonly', 'linter_warnings', 'linter_errors', 'linter_ok']]
\ },
\ 'component_expand': {
\   'linter_warnings': 'LightlineLinterWarnings',
\   'linter_errors': 'LightlineLinterErrors',
\   'linter_ok': 'LightlineLinterOK'
\ },
\ 'component_type': {
\   'readonly': 'error',
\   'linter_warnings': 'warning',
\   'linter_errors': 'error'
\ },
\ }

function! LightlineLinterWarnings() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '' : printf('%d ◆', all_non_errors)
endfunction

function! LightlineLinterErrors() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '' : printf('%d ✗', all_errors)
endfunction

function! LightlineLinterOK() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '✓ ' : ''
endfunction

autocmd User ALELint call s:MaybeUpdateLightline()

" Update and show lightline but only if it's visible (e.g., not in Goyo)
function! s:MaybeUpdateLightline()
  if exists('#lightline')
    call lightline#update()
  end
endfunction

"Need to set coloscheme after vundles are loaded
" silent! colorscheme badwolf
silent! colorscheme molokai
hi Folded guibg=#3e3e3e
hi Folded guifg=#b0b0b0
"set background=light             "Options are 'dark' or 'light'

function! s:goyo_enter()
    colorscheme pencil
endfunction

function! s:goyo_leave()
    colorscheme molokai
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()


