###### ===== THE BEST ZSHRC FILE EVER by Sam Paul ===== ######
DOTFILES=$HOME/dotfiles
SOURCES=$DOTFILES/sources
LINKS=$DOTFILES/links
NOT_PUBLIC=$HOME/dropbox/!public

# ===== OH-MY-ZSH ========
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="sampaul"
SYNTAX_DIR=$ZSH/custom/plugins/zsh-syntax-highlighting

#clone zsh-syntax-highlighting if its not there
[[ ! -d "$SYNTAX_DIR" ]] && git clone git://github.com/zsh-users/zsh-syntax-highlighting.git $SYNTAX_DIR

plugins=(brew command-not-found history jira gem osx python web-search mvn pip zsh-syntax-highlighting)
[[ -f "$ZSH/oh-my-zsh.sh" ]] && source $ZSH/oh-my-zsh.sh

# ===== SHELL GIT-STATUS =====
[[ -f "$SOURCES/gitstatus.sh" ]] && source $SOURCES/gitstatus.sh

# ===== ENV VARIABLES =====
[[ -f "$NOT_PUBLIC/envvars" ]] && source $NOT_PUBLIC/envvars

# export DOCKER_HOST=tcp://192.168.59.103:2376
# export DOCKER_CERT_PATH=/Users/sampaul/.boot2docker/certs/boot2docker-vm
# export DOCKER_TLS_VERIFY=1

# ===== HISTORY =====
[[ -f "$SOURCES/history" ]] && source $SOURCES/history

# ===== ALIASES =====
[[ -f "$SOURCES/aliases" ]] && source $SOURCES/aliases

# ===== DOCURATED ALIASES =====
[[ -f "$SOURCES/docurated_aliases" ]] && source $SOURCES/docurated_aliases

# ===== $PATH ========
# export PATH=/usr/local/bin:/usr/local/sbin:/bin:/usr/sbin:/sbin:/usr/bin:/opt/X11/bin:$PATH
# export PATH=$PATH:/Users/sampaul/Library/Python/2.7/bin
# export PATH="/usr/local/heroku/bin:$PATH"

# Use vi-mode in the shell
bindkey -v
bindkey -M viins 'jj' vi-cmd-mode #map jj to exit (mimic ESC)

# initialize pyenv (if it exists)
[[ -d "$HOME/.pyenv" ]] && eval "$(pyenv init -)"

# Virtualenv/VirtualenvWrapper
#export WORKON_HOME=$HOME/.virtualenvs
#source ~/.pyenv/shims/virtualenvwrapper.sh

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
typeset -U path

# =============== Autocomplete Stuff ==============
# source ~/.zsh-autosuggestions/autosuggestions.zsh
# Enable autosuggestions automatically
# zle-line-init() {
#     zle autosuggest-start
# }
# zle -N zle-line-init
# use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
# zsh-autosuggestions is designed to be unobtrusive)
# bindkey '^T' autosuggest-toggle
# Auto completion for git aliased as g
# complete -o bashdefault -o default -o nospace -F _git g 2>/dev/null \
#         || complete -o default -o nospace -F _git g

