###### ===== THE BEST ZSHRC FILE EVER by Sam Paul ===== ######
DOTFILES=$HOME/dotfiles
SOURCES=$DOTFILES/sources
LINKS=$DOTFILES/links
NOT_PUBLIC=$HOME/dropbox/!public
OPT_DIR=/usr/local/opt

# ===== OH-MY-ZSH ========
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="sampaul"
SYNTAX_DIR=$ZSH/custom/plugins/zsh-syntax-highlighting

plugins=(jira gem pip zsh-syntax-highlighting)
[[ -f "$ZSH/oh-my-zsh.sh" ]] && source $ZSH/oh-my-zsh.sh

#clone zsh-syntax-highlighting if its not there
[[ ! -d "$SYNTAX_DIR" ]] && git clone git://github.com/zsh-users/zsh-syntax-highlighting.git $SYNTAX_DIR

# ===== SHELL GIT-STATUS =====
[[ -d "$OPT_DIR/zsh-git-prompt" ]] && source $OPT_DIR/zsh-git-prompt/zshrc.sh
[[ -d "$OPT_DIR/zsh-git-prompt/.stack-work" ]] && GIT_PROMPT_EXECUTABLE="haskell"
ZSH_THEME_GIT_PROMPT_CHANGED="%{$FG[009]%}%{✚%G%}"

# ===== ENV VARIABLES =====
[[ -f "$NOT_PUBLIC/links/envvars" ]] && source $NOT_PUBLIC/links/envvars

# ===== HISTORY =====
[[ -f "$SOURCES/history" ]] && source $SOURCES/history

# ===== ALIASES =====
[[ -f "$SOURCES/aliases" ]] && source $SOURCES/aliases

# ===== DOCURATED ALIASES =====
[[ -f "$SOURCES/docurated_aliases" ]] && source $SOURCES/docurated_aliases

# ===== EXPORTS =====
[[ -f "$SOURCES/exports" ]] && source $SOURCES/exports

# initialize pyenv (if it exists)
[[ -d "$HOME/.pyenv" ]] && eval "$(pyenv init -)"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
typeset -U path

# Use vi-mode in the shell
bindkey -v
bindkey -M viins 'jj' vi-cmd-mode #map jj to exit (mimic ESC)
# backspace and ^h working even after returning from command mode
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char


# =============== Autocomplete Stuff ==============
# source ~/.zsh-autosuggestions/autosuggestions.zsh
# Enable autosuggestions automatically
# zle-line-init() {
#     zle autosuggest-start
# }
# zle -N zle-line-init
# use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
# zsh-autosuggestions is designed to be unobtrusive)
# bindkey '^T' autosuggest-toggle
# Auto completion for git aliased as g
# complete -o bashdefault -o default -o nospace -F _git g 2>/dev/null \
#         || complete -o default -o nospace -F _git g

